name: DEV CI/CD

on:
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_VERSION: '20.x'

jobs:
  build:
    name: Build and deploy to DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Read version
        id: package_version
        run: echo "current-version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build code
        env:
          REACT_APP_BUILD_ID: ${{ github.run_number }}-${{ github.run_id }}
        run: npm run build:dev

      - name: Build widget
        run: |
          npm run widget:dev

      - name: Copy widget
        run: |
          version=$(echo "v${{ steps.package_version.outputs.current-version }}" | cut -d '.' -f1-2)

          mkdir -p ./build/widget/$version-chunks
          cp ./widget/static/js/main.*.js ./build/widget/$version
          cp ./widget/static/css/main.*.css ./build/widget/$version.css
          cp ./widget/$version-chunks/*.chunk.js ./build/widget/$version-chunks
          cp ./widget/$version-chunks/*.chunk.css ./build/widget/$version-chunks
          cp ./widget/$version-chunks/*.wasm ./build/widget/$version-chunks

          sed -i "s|main-widget.css|https://dev.app.dfx.swiss/widget/$version.css|g" "./build/widget/$version"

      - name: Install Wrangler
        run: npm install -g wrangler@4

      - name: Deploy to Cloudflare Pages (DEV)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: wrangler pages deploy build --project-name=dfx-app-dev --branch=develop
